version: '3.8'

services:
  web:
    build: .
    container_name: portfolio_web
    ports:
      - "2004:80"
    volumes:
      - /Users/baptistep/Documents/developpement-web/portfolio:/var/www/html
    restart: always